# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cancer_type', models.CharField(max_length=250)),
                ('blood_group', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer.User'),
        ),
    ]
