# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0003_auto_20170410_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('history', models.FileField(max_length=1000, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.FileField(max_length=250, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer.User'),
        ),
    ]
