# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0004_auto_20170412_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_id',
        ),
    ]
