# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0007_auto_20170417_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
