# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0008_query_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='query',
            name='audio_file',
        ),
    ]
